name: CI Test

on: [push, pull_request]

jobs:
  mininet:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install latest Mininet
      shell: bash
      run: |
        sudo apt update
        cd /tmp
        git clone git://github.com/mininet/mininet
        cd mininet
        util/install.sh -v -n
        sudo mn --switch ovsbr --test pingall
    - name: Install deps
      shell: bash
      run: |
        sudo apt install -y iperf3
        sudo pip3 install -r requirements.txt
    - name: Test single host
      shell: bash
      run: |
        sudo python3 bbr.py --debug -c cubic -t 2 # bbr is not available in the image
    - name: Test batch run script
      shell: bash
      run: |
        sudo ./run mininet -t 1 --rtt-range 5 10 --bw-range 10 20 --size 0.1 --cc1 cubic -o batch
        # use the utility script to ensure we have proper data
        python3 util.py batch
    - name: Test plot script
      shell: bash
      run: |
        python3 plot.py heatmap -i batch/ batch/ -x rtt -y bw -t goodput -o test.png
        # make sure we generate the test.png properly
        find . -name test.png | grep .
